<a href="https://colab.research.google.com/github/Aswinab17/ML-algorithms/blob/main/obseityclassicfication_knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/Obesity Classification.csv')
df

ID  Age  Gender  Height  Weight   BMI          Label
0      1   25    Male     175      80  25.3  Normal Weight
1      2   30  Female     160      60  22.5  Normal Weight
2      3   35    Male     180      90  27.3     Overweight
3      4   40  Female     150      50  20.0    Underweight
4      5   45    Male     190     100  31.2          Obese
..   ...  ...     ...     ...     ...   ...            ...
103  106   11    Male     175      10   3.9    Underweight
104  107   16  Female     160      10   3.9    Underweight
105  108   21    Male     180      15   5.6    Underweight
106  109   26  Female     150      15   5.6    Underweight
107  110   31    Male     190      20   8.3    Underweight

[108 rows x 7 columns]

In [37]:
df.isna().sum()

ID        0
Age       0
Gender    0
Height    0
Weight    0
BMI       0
Label     0
dtype: int64

In [38]:
df.dtypes

ID          int64
Age         int64
Gender     object
Height      int64
Weight      int64
BMI       float64
Label      object
dtype: object

In [39]:
df=df.drop(['ID'],axis=1)


In [40]:
df

Age  Gender  Height  Weight   BMI          Label
0     25    Male     175      80  25.3  Normal Weight
1     30  Female     160      60  22.5  Normal Weight
2     35    Male     180      90  27.3     Overweight
3     40  Female     150      50  20.0    Underweight
4     45    Male     190     100  31.2          Obese
..   ...     ...     ...     ...   ...            ...
103   11    Male     175      10   3.9    Underweight
104   16  Female     160      10   3.9    Underweight
105   21    Male     180      15   5.6    Underweight
106   26  Female     150      15   5.6    Underweight
107   31    Male     190      20   8.3    Underweight

[108 rows x 6 columns]

In [41]:

from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
df['Gender']=lb.fit_transform(df['Gender'])
df['Label']=lb.fit_transform(df['Label'])
df

Age  Gender  Height  Weight   BMI  Label
0     25       1     175      80  25.3      0
1     30       0     160      60  22.5      0
2     35       1     180      90  27.3      2
3     40       0     150      50  20.0      3
4     45       1     190     100  31.2      1
..   ...     ...     ...     ...   ...    ...
103   11       1     175      10   3.9      3
104   16       0     160      10   3.9      3
105   21       1     180      15   5.6      3
106   26       0     150      15   5.6      3
107   31       1     190      20   8.3      3

[108 rows x 6 columns]

In [42]:
x=df.iloc[:,:-1].values
x

array([[ 25. ,   1. , 175. ,  80. ,  25.3],
       [ 30. ,   0. , 160. ,  60. ,  22.5],
       [ 35. ,   1. , 180. ,  90. ,  27.3],
       [ 40. ,   0. , 150. ,  50. ,  20. ],
       [ 45. ,   1. , 190. , 100. ,  31.2],
       [ 50. ,   0. , 140. ,  40. ,  16.7],
       [ 55. ,   1. , 200. , 110. ,  34.2],
       [ 60. ,   0. , 130. ,  30. ,  13.3],
       [ 65. ,   1. , 210. , 120. ,  37.2],
       [ 70. ,   0. , 120. ,  20. ,  10. ],
       [ 18. ,   1. , 175. ,  70. ,  23.4],
       [ 23. ,   0. , 160. ,  50. ,  20. ],
       [ 28. ,   1. , 180. ,  80. ,  25.3],
       [ 33. ,   0. , 150. ,  60. ,  22.5],
       [ 38. ,   1. , 190. ,  90. ,  27.3],
       [ 43. ,   0. , 140. ,  50. ,  20. ],
       [ 48. ,   1. , 200. , 100. ,  31.2],
       [ 53. ,   0. , 130. ,  40. ,  16.7],
       [ 58. ,   1. , 210. , 110. ,  34.2],
       [ 63. ,   0. , 120. ,  30. ,  13.3],
       [ 68. ,   1. , 175. ,  80. ,  25.3],
       [ 73. ,   0. , 160. ,  60. ,  22.5],
       [ 78. ,   1. , 180. ,  90

In [43]:
y=df.iloc[:,-1].values
y

array([0, 0, 2, 3, 1, 3, 1, 3, 1, 3, 0, 3, 0, 0, 2, 3, 1, 3, 1, 3, 0, 0,
       2, 3, 1, 3, 1, 3, 1, 0, 0, 2, 2, 2, 1, 2, 1, 2, 0, 3, 0, 0, 2, 0,
       2, 2, 1, 2, 0, 3, 0, 0, 2, 0, 2, 2, 1, 2, 0, 3, 0, 3, 0, 0, 2, 0,
       2, 2, 3, 3, 0, 3, 0, 3, 0, 0, 2, 0, 3, 3, 3, 3, 0, 3, 3, 3, 3, 3,
       3, 3, 3, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [44]:
from sklearn.model_selection import train_test_split
x_test,x_train,y_test,y_train=train_test_split(x,y,test_size=0.30,random_state=42)
x_test

array([[ 44. ,   0. , 140. ,  75. ,  25. ],
       [102. ,   0. , 130. ,  75. ,  25. ],
       [ 11. ,   1. , 175. ,  10. ,   3.9],
       [108. ,   1. , 210. , 120. ,  37.2],
       [ 27. ,   1. , 180. ,  75. ,  24.2],
       [ 50. ,   0. , 140. ,  40. ,  16.7],
       [ 92. ,   0. , 140. ,  65. ,  22.7],
       [ 31. ,   1. , 190. ,  20. ,   8.3],
       [ 22. ,   0. , 160. ,  45. ,  18.7],
       [ 54. ,   0. , 130. ,  85. ,  27.5],
       [ 48. ,   1. , 200. , 100. ,  31.2],
       [ 14. ,   1. , 175. ,  35. ,  16.7],
       [ 49. ,   1. , 200. , 105. ,  28.9],
       [ 56. ,   1. , 210. ,  95. ,  27. ],
       [ 60. ,   0. , 130. ,  30. ,  13.3],
       [ 42. ,   0. , 140. ,  65. ,  22.7],
       [ 51. ,   0. , 130. ,  65. ,  22.7],
       [ 35. ,   1. , 190. ,  65. ,  22.7],
       [103. ,   0. , 130. ,  30. ,  13.3],
       [ 63. ,   0. , 120. ,  30. ,  13.3],
       [ 48. ,   0. , 130. ,  40. ,  16.7],
       [ 21. ,   1. , 180. ,  15. ,   5.6],
       [ 93. ,   0. , 140. ,  40

In [45]:
x_test

array([[ 44. ,   0. , 140. ,  75. ,  25. ],
       [102. ,   0. , 130. ,  75. ,  25. ],
       [ 11. ,   1. , 175. ,  10. ,   3.9],
       [108. ,   1. , 210. , 120. ,  37.2],
       [ 27. ,   1. , 180. ,  75. ,  24.2],
       [ 50. ,   0. , 140. ,  40. ,  16.7],
       [ 92. ,   0. , 140. ,  65. ,  22.7],
       [ 31. ,   1. , 190. ,  20. ,   8.3],
       [ 22. ,   0. , 160. ,  45. ,  18.7],
       [ 54. ,   0. , 130. ,  85. ,  27.5],
       [ 48. ,   1. , 200. , 100. ,  31.2],
       [ 14. ,   1. , 175. ,  35. ,  16.7],
       [ 49. ,   1. , 200. , 105. ,  28.9],
       [ 56. ,   1. , 210. ,  95. ,  27. ],
       [ 60. ,   0. , 130. ,  30. ,  13.3],
       [ 42. ,   0. , 140. ,  65. ,  22.7],
       [ 51. ,   0. , 130. ,  65. ,  22.7],
       [ 35. ,   1. , 190. ,  65. ,  22.7],
       [103. ,   0. , 130. ,  30. ,  13.3],
       [ 63. ,   0. , 120. ,  30. ,  13.3],
       [ 48. ,   0. , 130. ,  40. ,  16.7],
       [ 21. ,   1. , 180. ,  15. ,   5.6],
       [ 93. ,   0. , 140. ,  40

In [46]:
# from sklearn.preprocessing import StandardScaler
# scalar=StandardScaler()
# scalar.fit(x_train)
# x_train=scalar.transform(x_train)
# x_test=scalar.transform(x_test)
#normalization
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)     #z=(x-u)/s
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [47]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
y_pred

array([2, 2, 3, 1, 0, 3, 2, 3, 3, 2, 1, 3, 2, 2, 3, 0, 2, 0, 3, 3, 3, 3,
       3, 3, 3, 3, 1, 3, 3, 0, 1, 3, 1, 0, 3, 3, 1, 2, 3, 1, 3, 3, 3, 3,
       3, 0, 2, 3, 2, 2, 2, 3, 3, 3, 2, 2, 0, 3, 3, 1, 2, 0, 2, 3, 3, 2,
       3, 0, 2, 0, 3, 2, 3, 2, 3])

In [48]:
y_test

array([2, 2, 3, 1, 0, 3, 0, 3, 3, 2, 1, 3, 1, 2, 3, 0, 0, 0, 3, 3, 3, 3,
       3, 3, 3, 0, 1, 3, 3, 0, 1, 3, 1, 0, 3, 3, 2, 0, 3, 1, 3, 3, 3, 3,
       0, 0, 0, 3, 2, 0, 2, 3, 3, 0, 0, 2, 0, 3, 0, 2, 0, 2, 3, 3, 3, 0,
       3, 0, 0, 0, 3, 2, 3, 0, 3])

In [50]:
from sklearn.metrics import confusion_matrix,accuracy_score
cmd=confusion_matrix(y_test,y_pred)
print(cmd)


[[ 9  0 10  4]
 [ 0  6  1  0]
 [ 1  2  8  0]
 [ 0  0  1 33]]


In [51]:
acc=accuracy_score(y_test,y_pred)
print(acc)

0.7466666666666667
